# Docker Compose sonarr
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/sonarr:/config
      - ${MediaDir}/video/tv-shows:/tv
      - ${MediaDir}/downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: always
    networks:
      - backend
    depends_on:
      - sabnzbd
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
