# Docker Compose bazarr
version: "3.8" # Specify Docker Compose version for compatibility

services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped # Updated restart policy for better control
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/bazarr/config:/config
      - ${MediaDir}/video/movies:/movies
      - ${MediaDir}/video/tv-shows:/tv
    ports:
      - 6767:6767
    networks:
      backend:
        aliases:
          - bazarr
    depends_on:
      radarr:
        condition: service_started # Updated to "service_started" due to Docker Compose limitations for health checks
      sonarr:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767 || exit 1"] # Adjusted for localhost reliability
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    external: true