services:
  mysql:
    image: mysql:8.0
    container_name: semaphore_mysql
    restart: unless-stopped
    hostname: mysql
    volumes:
      - ${DockerDir}/semaphore/mysql:/var/lib/mysql # Persistent MySQL data stored on NAS
    environment:
      PUID: ${PUID} # User ID (from environment variables)
      PGID: ${PGID} # Group ID (from environment variables)
      TZ: ${TZ} # Timezone configuration (from environment variables)
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${MYSQLUser}
      MYSQL_PASSWORD: ${MYSQLPassword}
    networks:
      backend:
        aliases:
          - mysql-db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    ports:
      - "3100:3000" # Map port 3100 on the host to port 3000 in the container
    environment:
      PUID: ${PUID} # User ID (from environment variables)
      PGID: ${PGID} # Group ID (from environment variables)
      TZ: ${TZ} # Timezone configuration (from environment variables)
      SEMAPHORE_DB_USER: ${MYSQLUser}
      SEMAPHORE_DB_PASS: ${MYSQLPassword}
      SEMAPHORE_DB_HOST: mysql-db # Using alias for MySQL service
      SEMAPHORE_DB_PORT: 3306 # MySQL port
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/repository/playbooks
      ANSIBLE_CONFIG: /tmp/semaphore/repository/ansible.cfg
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHOREPassword}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMPAPHOREKey}
      SEMAPHORE_LDAP_ACTIVATED: 'no' # Disabled LDAP integration
    depends_on:
      - mysql # Ensure MySQL starts before Semaphore
    volumes:
      - ${DockerDir}/semaphore/data:/data # Persist service data to host directory
      - ${DockerDir}/semaphore/data/id_ed25519_ansible.git:/root/.ssh/id_ed25519_ansible.git:ro # Mount private key (read-only)
      - ${DockerDir}/semaphore/data/id_ed25519_ansible.git.pub:/root/.ssh/id_ed25519_ansible.git.pub:ro # Mount public key (read-only)
      - ${DockerDir}/semaphore/data/ssh_config:/root/.ssh/config:ro # Mount SSH config (read-only)
    networks:
      backend:
        aliases:
          - semaphore-app
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://semaphore-app:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    external: true