# Docker compose radarr

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped # Updated restart policy for better control
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/radarr:/config
      - ${MediaDir}/video/movies:/movies
      - ${MediaDir}/downloads/complete:/downloads
    ports:
      - 7878:7878
    networks:
      backend:
        aliases:
          - radarr
    depends_on:
      sabnzbd:
        condition: service_started # Adjusted condition (Docker Compose does not support healthcheck dependencies)
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878 || exit 1"] # Corrected to use localhost inside the container
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    external: true