# Define global networks
networks:
  backend:
    driver: bridge

# Define shared volumes
volumes:
  docker_sock:
    driver: local

# Include services
services:
  autoheal:
    extends:
      file: ./docker-compose.autoheal.yml
      service: autoheal

  nginx-proxy-manager:
    extends:
      file: ./docker-compose.nginx.yml
      service: nginx-proxy-manager

  sabnzbd:
    extends:
      file: ./docker-compose.sabnzbd.yml
      service: sabnzbd

  radarr:
    extends:
      file: ./docker-compose.radarr.yml
      service: radarr
      
  sonarr:
    extends:
      file: ./docker-compose.sonarr.yml
      service: sonarr

  homepage:
    extends:
      file: ./docker-compose.homepage.yml
      service: homepage

  bazarr:
    extends:
      file: ./docker-compose.bazarr.yml
      service: bazarr
