#Xen Orchestrata
services:
    xen-orchestra:
        restart: unless-stopped
        image: ronivay/xen-orchestra:latest
        container_name: xen-orchestra
        stop_grace_period: 1m
        ports:
            - "60:80"
            - "6443:443"
        environment:
            - PUID=${PUID}       # User ID for permission management
            - PGID=${PGID}       # Group ID for permission management
            - TZ=${TZ}           # Timezone for accurate logs and schedules
            - HTTP_PORT=80
            - HTTPS_PORT=443
            - REDIRECT_TO_HTTPS=true
        cap_add:
          - SYS_ADMIN
          - DAC_READ_SEARCH
        security_opt:
          - apparmor:unconfined
        volumes:
          - ${DockerDir}/xo-data:/var/lib/xo-server # Persistent storage for Xen Orchestra data
          - ${DockerDir}/redis-data:/var/lib/redis # Storage for Redis data
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "2"

volumes:
  xo-data:
  redis-data:
  
networks:
  backend:
    external: true