# Docker Compose Autoheal 
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - docker_sock:/var/run/docker.sock
    networks:
      - backend

