# Docker Compose file for deploying Ansible Semaphore
services:
  mysql:
    image: mysql:8.0
    container_name: semaphore_mysql
    restart: unless-stopped
    hostname: mysql
    volumes:
      - ${DockerDir}/semaphore/mysql:/var/lib/mysql # Persistent MySQL data stored on NAS
    environment:
      PUID: ${PUID} # User ID (from environment variables)
      PGID: ${PGID} # Group ID (from environment variables)
      TZ: ${TZ} # Timezone configuration (from environment variables)
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${MYSQLUser}
      MYSQL_PASSWORD: ${MYSQLPassword}
    networks:
      - backend

  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    ports:
      - "3100:3000" # Map port 3100 on the host to port 3000 in the container
    environment:
      PUID: ${PUID} # User ID (from environment variables)
      PGID: ${PGID} # Group ID (from environment variables)
      TZ: ${TZ} # Timezone configuration (from environment variables)
      SEMAPHORE_DB_USER: ${MYSQLUser}
      SEMAPHORE_DB_PASS: ${MYSQLPassword}
      SEMAPHORE_DB_HOST: mysql # The MySQL service hostname
      SEMAPHORE_DB_PORT: 3306 # MySQL port
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHOREPassword}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: SEMPAPHOREKey
      SEMAPHORE_LDAP_ACTIVATED: 'no' # Set to 'yes' to enable LDAP

    depends_on:
      - mysql # Ensure mysql starts before semaphore
    volumes:
      - ${DockerDir}/semaphore/data:/data  # Persist service data to host directory
      - ${Ansible_SSH_KEY_PATH}:/data/id_ed25519
      
    networks:
      - backend
