# Docker Compose Autoheal 
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
      - PUID=${PUID}       # User ID for permission management
      - PGID=${PGID}       # Group ID for permission management
      - TZ=${TZ}           # Timezone for accurate logs and schedules
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M # Limit the memory usage to 128MB
          cpus: '0.50' # Restrict CPU usage to 50% of a single core
        reservations:
          memory: 64M  # Reserve 64MB of memory as a minimum
          cpus: '0.25' # Reserve 25% of a single core

volumes:
  docker_sock:
networks:
  backend:
    external: true
