#Docker Compose master file 


# Define global networks
networks:
  backend:
    driver: bridge # Central network for backend service communication

# Define shared volumes
volumes:
  docker_sock:
    driver: local # Shared Docker socket volume for containers that require API access

# Include all services
services:
  autoheal:
    # Automatically restarts unhealthy containers
    extends:
      file: ./docker-compose.autoheal.yml
      service: autoheal

  nginx-proxy-manager:
    # Manage reverse proxy configurations via a web interface
    extends:
      file: ./docker-compose.nginx.yml
      service: nginx-proxy-manager

  sabnzbd:
    # Usenet download client for automated downloading
    extends:
      file: ./docker-compose.sabnzbd.yml
      service: sabnzbd

  radarr:
    # Automated movie management and download scheduling
    extends:
      file: ./docker-compose.radarr.yml
      service: radarr

  sonarr:
    # Automated TV show management and download scheduling
    extends:
      file: ./docker-compose.sonarr.yml
      service: sonarr

  homepage:
    # Centralized access to services and tools
    extends:
      file: ./docker-compose.homepage.yml
      service: homepage

  bazarr:
    # Subtitle management for movies and TV shows
    extends:
      file: ./docker-compose.bazarr.yml
      service: bazarr

  semaphore:
    # Ansible-based task and playbook automation tool
    extends:
      file: ./docker-compose.semaphore.yml
      service: semaphore

  mysql:
    # MySQL database for Semaphore
    extends:
      file: ./docker-compose.semaphore.yml
      service: mysql

# Placeholder for currently unused services
# Uncomment and use as needed
# xen-orchestra:
#   # Manage virtualization infrastructure
#   extends:
#     file: ./docker-compose.xo.yml
#     service: xen-orchestra

# gluetun:
#   # VPN container for securing internet traffic
#   extends:
#     file: ./docker-compose.gluetun.yml
#     service: gluetun

# unifi-controller:
#   # Unified controller for managing network devices
#   extends:
#     file: ./docker-compose.unifi.yml
#     service: unifi-controller