# Docker Compose bazarr
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/bazarr/config:/config
      - ${MediaDir}/video/movies:/movies
      - ${MediaDir}/video/tv-shows:/tv
    ports:
      - 6767:6767
    restart: always
    networks:
      - backend
    depends_on:
      - sabnzbd
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3