   # Networks
networks:
   backend:
      driver: bridge
   # Services
services:

   # Autoheal
   autoheal:
      restart: always
      image: willfarrell/autoheal
      environment:
         - AUTOHEAL_CONTAINER_LABEL=all
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - backend

   # NGINX Proxy Manager
   nginx-proxy-manager:
      image: jc21/nginx-proxy-manager:latest
      container_name: nginx-proxy-manager
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      ports:
         - 80:80
         - 443:443
         - 81:81
      volumes:
         - ${DockerDir}/nginx_pm/data:/data
         - ${DockerDir}/nginx_pm/letsencrypt:/etc/letsencrypt
         - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      networks:
         - backend
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:81 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3

   # SABNZBD
   sabnzbd:
      image: linuxserver/sabnzbd
      container_name: sabnzbd
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      volumes:
         - ${DockerDir}/sabnzbd:/config
         - ${MediaDir}/downloads/complete:/downloads 
         - ${MediaDir}/downloads/incomplete:/incomplete-downloads
      ports:
         - 8080:8080
      restart: always
      networks:
         - backend
      depends_on:
         - nginx-proxy-manager
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3

   # Radarr
   radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      volumes:
         - ${DockerDir}/radarr:/config
         - ${MediaDir}/video/movies:/movies
         - ${MediaDir}/downloads/complete:/downloads 
      ports:
         - 7878:7878
      restart: always
      networks:
         - backend
      depends_on:
         - sabnzbd
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:7878 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3

   # Sonarr
   sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      volumes:
         - ${DockerDir}/sonarr:/config
         - ${MediaDir}/video/tv-shows:/tv 
         - ${MediaDir}/downloads/complete:/downloads
      ports:
         - 8989:8989
      restart: always
      networks:
         - backend
      depends_on:
         - sabnzbd
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:8989 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3
   # Homepage
   homepage:
      image: ghcr.io/gethomepage/homepage:latest
      container_name: homepage
      environment:
      #Common
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
         # URLS
         - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
         - HOMEPAGE_VAR_CockpitURL=${HOMEPAGE_VAR_CockpitURL}
         - HOMEPAGE_VAR_DockerURL=${HOMEPAGE_VAR_DockerURL}
         - HOMEPAGE_VAR_HomeAssistantURL=${HOMEPAGE_VAR_HomeAssistantURL}
         - HOMEPAGE_VAR_HomeserverURL=${HOMEPAGE_VAR_HomeserverURL}
         - HOMEPAGE_VAR_NGINXProxyURL=${HOMEPAGE_VAR_NGINXProxyURL}
         - HOMEPAGE_VAR_PlexURL=${HOMEPAGE_VAR_PlexURL}
         - HOMEPAGE_VAR_RadarrURL=${HOMEPAGE_VAR_RadarrURL}
         - HOMEPAGE_VAR_SabnzbdURL=${HOMEPAGE_VAR_SabnzbdURL}
         - HOMEPAGE_VAR_SonarrURL=${HOMEPAGE_VAR_SonarrURL}
         - HOMEPAGE_VAR_UnifiURL=${HOMEPAGE_VAR_UnifiURL}
         - HOMEPAGE_VAR_XCPNG1URL=${HOMEPAGE_VAR_XCPNG1URL}
         - HOMEPAGE_VAR_XOURL=${HOMEPAGE_VAR_XOURL}
         # Authentication
         - HOMEPAGE_VAR_RadarrAPI=${HOMEPAGE_VAR_RadarrAPI}
         - HOMEPAGE_VAR_SonarrAPI=${HOMEPAGE_VAR_SonarrAPI}
         - HOMEPAGE_VAR_SabnzbdAPI=${HOMEPAGE_VAR_SabnzbdAPI}
         - HOMEPAGE_VAR_CoinmarketcapAPI=${HOMEPAGE_VAR_CoinmarketcapAPI}
         - HOMEPAGE_VAR_HomeAssistantAPI=${HOMEPAGE_VAR_HomeAssistantAPI}
         - HOMEPAGE_VAR_openweathermapAPI=${HOMEPAGE_VAR_openweathermapAPI}
         - HOMEPAGE_VAR_NasUser=${HOMEPAGE_VAR_NasUser}
         - HOMEPAGE_VAR_NASPassword=${HOMEPAGE_VAR_NASPassword}
         - HOMEPAGE_VAR_NGINXUsername=${HOMEPAGE_VAR_NGINXUsername}
         - HOMEPAGE_VAR_NGINXPassword=${HOMEPAGE_VAR_NGINXPassword}
      ports:
         - 3000:3000
      volumes:
         - ${DockerDir}/homepage:/app/config
         - ${DockerDir}/homepage/public/icons:/app/public/icons
         - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      depends_on:
         - nginx-proxy-manager
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:3000|| exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3
      networks:
         - backend
