# Docker Compose Autoheal 
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped # Updated restart policy for better control
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=30
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      backend:
        aliases:
          - autoheal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M # Enforce a memory limit of 128MB
          cpus: '0.50' # Restrict CPU usage to 50% of a single core
        reservations:
          memory: 64M  # Reserve 64MB of memory as a minimum
          cpus: '0.25' # Reserve 25% of a single core

networks:
  backend:
    external: true
