# Docker Compose NGINX Proxy Manager 

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped # Updated restart policy for better control
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 80:80    # HTTP traffic
      - 443:443  # HTTPS traffic
      - 81:81    # Admin interface
    volumes:
      - ${DockerDir}/nginx_pm/data:/data           # Persistent storage for service data
      - ${DockerDir}/nginx_pm/letsencrypt:/etc/letsencrypt # Persistent storage for SSL certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use the already-defined Docker socket
    networks:
      backend:
        aliases:
          - nginx-proxy-manager
    depends_on:
      autoheal:
        condition: service_started # Adjusted depends_on condition
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:81 || exit 1"] # Adjusted health check for reliability
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    external: true